#!/usr/bin/env node

// mvregex - A bash script for batch moving a set of files given 2 regexes
//
// Copyright (c) 2013 Neal Hardesty
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//

// NOTE, you must install the 'walk' npm module:
//     npm install walk

var walk = require('walk');
var dir = process.argv[3] || process.cwd();
var path = require('path');
var walker;
var fileexts = [".mp3", ".mp4", ".avi", ".mkv", ".mov", ".mpg"];
var selector = process.argv[2];
var selectorRegex;

if(process.argv[2] === '-h') {
	console.log("Usage: " + process.argv[1] + " <-h|selector regex> [directory (assumes cwd)]");
	process.exit(0);
}

if(selector) {
	selectorRegex=new RegExp(selector, 'i');
}

console.log("#EXTM3U");

walker = walk.walk(dir);

function isInteresting(filename) {
	for (var i in fileexts) {
		// check extension, then check selector if present
		if(fileexts[i] === path.extname(filename).toLowerCase()) {
			if(selectorRegex) {
				if(selectorRegex.test(filename)) {
					return true;
				}
			} else {
				return true;
			}
		}
	}
	return false;
}

function nameNormalize(filename) {
	return filename.replace(/\./g, " ");
}

walker.on("directories", function(root, dirStatsArray, next) {
	dirStatsArray.sort(function(a,b) {
		if(a > b) return -1;
		if(a < b) return 1;
		return 0;
	});
	next();
});

walker.on("file", function(root, fileStats, next) {
	var fullname=path.resolve(path.normalize(path.join(root, fileStats.name)));
	if(isInteresting(fullname)) {
		console.log("#EXTINF:-1," + nameNormalize(path.basename(fileStats.name, path.extname(fileStats.name))));
		console.log(fullname);
	}
	next();
});

walker.on("directories", function(root, dirStats, next) {
	dirStats.reverse();
	next();
});
